name: Docker Image CI for caddy

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "45 20 * * *"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image and Push the Docker image to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
          root=$(pwd)
          cd ${root}/docker-caddy/stable/debian
          docker buildx build --platform linux/amd64,linux/arm64 -t looprt/caddy:latest --push .
          cd ${root}/docker-caddy/stable/ubuntu
          docker buildx build --platform linux/amd64,linux/arm64 -t looprt/caddy:ubuntu-latest --push .

