name: Docker Image CI for ubuntu-latest

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "45 18 * * *"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          cd docker-serverstatus/stable/ubuntu/nginx
          docker build . --file Dockerfile --tag serverstatus_server

      - name: Push the Docker image to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
          docker tag serverstatus_server looprt/serverstatus_server:ubuntu-latest
          docker push looprt/serverstatus_server:ubuntu-latest
