name: Docker Image CI for serverstatus_server

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "45 18 * * *"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image and Push the Docker image to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
          cd docker-serverstatus/stable/ubuntu/caddy
          docker buildx build --platform linux/amd64,linux/arm64 -t looprt/serverstatus_server:ubuntu-caddy --push .
          cd docker-serverstatus/stable/ubuntu/nginx
          docker buildx build --platform linux/amd64,linux/arm64 -t looprt/serverstatus_server:ubuntu-latest --push .
          cd docker-serverstatus/stable/debian/caddy
          docker buildx build --platform linux/amd64,linux/arm64 -t looprt/serverstatus_server:caddy --push .
